package com.example.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Represents a payment entity in the system.
 * <p>
 * This class maps to a database table storing payment information,
 * including details about purchased products and their layouts.
 *
 * <p>Each payment record contains:
 * <ul>
 *   <li>Automatically generated unique identifier</li>
 *   <li>Product reference</li>
 *   <li>Layout reference</li>
 *   <li>Timestamp of when the payment was processed</li>
 * </ul>
 *
 * @see Entity
 * @see Getter
 * @see Setter
 * @see NoArgsConstructor
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Payment {

    /**
     * The unique identifier for this payment record.
     * <p>
     * Automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The identifier of the purchased product.
     * <p>
     * References a product in the product catalog.
     */
    private String productId;

    /**
     * The identifier of the product layout used.
     * <p>
     * References a specific layout configuration of the product.
     */
    private String layoutId;

    /**
     * The date and time when the payment was processed.
     * <p>
     * Automatically recorded when the payment entity is created.
     */
    private LocalDateTime timestamp;
}