package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a user entity in the system.
 * <p>
 * This entity maps to the 'allusers' database table and stores
 * essential authentication and authorization information.
 * It is used for security purposes throughout the application.
 *
 * <p>Contains:
 * <ul>
 *   <li>Unique system-generated identifier</li>
 *   <li>User credentials (username and encrypted password)</li>
 *   <li>Role-based authorization information</li>
 * </ul>
 *
 * @see Entity
 * @see Table
 * @see Getter
 * @see Setter
 * @see NoArgsConstructor
 */
@Entity
@Table(name = "allusers")
@Getter
@Setter
@NoArgsConstructor
public class User {

    /**
     * The unique identifier for the user.
     * <p>
     * Automatically generated by the database using identity column strategy.
     * Serves as the primary key for user records.
     *
     * @see Id
     * @see GeneratedValue
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique username for authentication.
     * <p>
     * Used as the principal identifier when logging in.
     * Must be unique across all users in the system.
     */
    private String username;

    /**
     * The encrypted password for authentication.
     * <p>
     * Should always be stored in encrypted form using a strong hashing algorithm.
     * Never stored or transmitted in plain text.
     */
    private String password;

    /**
     * The role assigned to the user for authorization.
     * <p>
     * Determines the user's permissions and access levels within the system.
     * Common values might include 'USER', 'ADMIN', etc.
     */
    private String role;
}