package com.example.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Represents a product view tracking entity in the system.
 * <p>
 * This entity records user view events for products and their specific layouts,
 * capturing the temporal dimension of user interactions. Used for analytics
 * and user behavior tracking purposes.
 *
 * <p>Each view record contains:
 * <ul>
 *   <li>Automatically generated unique identifier</li>
 *   <li>Product identification</li>
 *   <li>Layout configuration reference</li>
 *   <li>Precise event timestamp</li>
 * </ul>
 *
 * @see Entity
 * @see Getter
 * @see Setter
 * @see NoArgsConstructor
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
public class View {

    /**
     * The unique identifier for this view record.
     * <p>
     * Automatically generated by the persistence provider.
     * Serves as the primary key for view records.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The identifier of the viewed product.
     * <p>
     * References a specific product in the product catalog.
     * Used to aggregate view statistics by product.
     */
    private String productId;

    /**
     * The identifier of the viewed layout configuration.
     * <p>
     * Specifies which product layout variant was viewed.
     * Enables layout-specific performance analysis.
     */
    private String layoutId;

    /**
     * The exact date and time when the view occurred.
     * <p>
     * Recorded automatically when the view event is captured.
     * Enables temporal analysis of viewing patterns.
     */
    private LocalDateTime timestamp;
}